# Generated by Django 2.2.3 on 2019-07-20 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='loginTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
