# Generated by Django 2.2.3 on 2019-07-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeta',
            name='employeeName',
        ),
    ]
