# Generated by Django 2.2.3 on 2019-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0002_auto_20190720_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='loginTime',
            field=models.TimeField(),
        ),
    ]
