# Generated by Django 2.2.3 on 2019-07-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0003_auto_20190720_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='loginTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
