# Generated by Django 2.2.3 on 2019-07-16 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0003_auto_20190716_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='logoutTime',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
