# Generated by Django 2.2.2 on 2019-07-25 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0004_auto_20190720_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunchTimeStart', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
    ]
