# Generated by Django 2.2.2 on 2019-07-25 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empdailyreport', '0005_urltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltime',
            name='eveningend',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='urltime',
            name='eveningstart',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='urltime',
            name='lunchTimeEnd',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
